# Site settings
title:       Coding Struggles
email:       branch13@gmail.com
author:      Dario Oddenino
description: "Struggling to be a better coder :)"
baseurl:     ""
url:         "https://codingstruggles.com"
date_format: "%b %-d, %Y"

# Google services
google_verification: "4p9Idbj55gSFz5mSVYSiL0b1hjWGqKG8p1f1Uc2lVAA"
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: "UA-69458120-1"
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: "dariooddenino"

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: "dariooddenino"
bitbucket_username:
stackoverflow_id:
twitter_username: "dariooddenino"
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: true
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    none
post_dirs:    false
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

collections:
  recipes:
    output: true
    permalink: /ps-cookbook/:name


defaults:
  - scope:
      path: ''
      type: 'recipes'
    values:
      layout: 'recipe'
